--- 
title: "Russian influence on Iźva Komi sibilant articulation"
author: "Niko Partanen"
date: "`r Sys.Date()`"
bibliography: [bibliography.bib, packages.bib]
knit: "bookdown::render_book"
output:
  bookdown::gitbook:
    config:
      toc:
        before: null
        after: null
  bookdown::tufte_html_book:
    toc: yes
    css: toc.css
  bookdown::pdf_book:
    keep_tex: no
    latex_engine: xelatex
  bookdown::html_chapters: default
documentclass: book
link-citations: yes
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Preface

I'm presented this study at SLE 2016 conference in Naples. I've been working with it quite a while, and it connects in many ways to my PhD studies. Actually this page contains the whole study as it is, in whatever messy state it is, and Git version control allows tracing it back to the first lines I wrote. Scary, but in some sense also reassuring. At the moment I have the data locally, but in the later phase also this will be connected to a repository where it can be accessed, at least after request in case some materials cannot be openly shared. Open science has to look something like this, so that our data is available, as is our analysis and the road we took to get into it.

Quite a long time has passed since I submitted the abstract first time, and not everything has gone exactly as one would had thought. I thought I would had had a possibility to gather more data from Komi in Siberia, but we had many good reasons to work in Kola Peninsula during summer 2016 instead. Also many preliminary results have gone to the trashbin over and over again, but most of the ideas I propose still seem to hold.

## Abstract

The Uralic language Komi Zyrian distinguishes several **palatal consonants** as their own phonemes. This differs from the **palatalized consonants** found in Russian. In some varieties of the Iźva dialect, the sibilants /ɕ/ and /ʑ/ have shifted to a palatalized manner of articulation. This feature is often characteristic of the Komi spoken in Western Siberia and on the Kanin and Kola Peninsulas. It is also clear that other authors have perceived this difference, i.e. by transcribing with /ś/ and /š́/ what presumably is the difference between /sʲ/ and /ɕ/ (cf. Iźva varieties in [@uotila1986a] with many different sibilant allophones). Native speakers also occasionally comment on this feature. This change is likely, though not necessarily, induced by Russian contact. As a change within allophonic variants, this change has had no impact on the Komi phonological system. To make a comparison, this already makes the contact outcome different from that of other Uralic language, Kildin Saami, where Russian influence has slightly changed the phonotaxis of palatalized consonants, among other things, as analyzed by Blokland et al. [-@bloklandEtAl2011a, 16] and Kuzmenko et al. [-@kuzmenkoEtAl2012aTR].

I have examined this phenomenon in connection with the **adaptation of Russian loanwords in spoken Komi**. The latter topic has generally received some attention, i.e. [@igusev1972cTR]; for an overview of the language contact situation, see [@leinonen2009a]. Due to bilingualism, Komi speakers always have the option of pronouncing the sibilants in lexical items such as 'September' following the Russian or Komi model, respectively /sʲenʲtʲabrʲ/ or /ɕeɲcabr/, with variation in levels of adaptation. When analyzed in a modern sociolinguistic framework where variables are seen as expressions of styles and social identities, not as permanent attributes of the speakers, e.g. [@eckert2012a, 93–94], this variation can be described within the context where it occurs. Among the relevant factors, formality seems to be salient: speech in an educational setting, official speeches or interviews exhibit more standard Komi pronunciation than informal conversations. The social relevance of this variation is connected to the perception that the palatalized pronunciation is not native to Komi. However, while the palatalized pronunciation can be perceived as a Russian accent, an overly Komi pronunciation of Russian lexical items can also be interpreted as an inability to pronounce Russian – something that seems to be poorly accepted in modern Russia. One must also note that for some speakers the palatalized pronunciation can be considered the unmarked variant.

The analysis is based on a transcribed corpus of spoken Iźva Komi collected as part of a research project funded by Kone Foundation between 2014 and 2016. This larger body of data has been sampled so that there are examples from different age groups and different areas where Iźva Komi is spoken. Tools of phonetic analysis are used to measure the different variables and the distribution and relevance of the results are validated with statistical tests. In 2016, the material will be stored and archived in different repositories with the rest of the Komi corpus, making them available for scientific use and ensuring the reproducibility of the research.

## About using GitHub pages

One of the key reasons to manage the project this way publicly in GitHub is that it really ensures the reproducibility of the study. It isn't necessarily so important for the others, but it is also easier for me to manage what is going on while the project is rigorously under version control. And so is the language documentation corpus the study is based upon. It is natural that in many cases the researchers cannot share all of their raw data, the main reasons being connected to the rights of those individuals from who the data has been collected. This is of course normal in human sciences. Sharing the research in prose form is also a norm, but as the datasets used are getting more complicated, there is also more use of computational tools. Sharing these tools should be as natural as sharing the more literal content of your work. This is one way to do it nicely, in my opinion.
